version: '2'

services:
  burger-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: burger-api
    restart: on-failure
    ports:
      - '5000:5000'
    networks:
      - burger-network
    depends_on:
      - burger-db
    environment:
      - PORT=5000
      - dbHost=burger-db
      - dbPort=5432
      - dbUsername=postgres
      - dbPassword=postgres
      - dbName=postgres

  burger-db:
    image: postgres
    container_name: burger-db
    command: postgres -c 'max_connections=10'
    networks:
      - burger-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  burger-network:
    driver: bridge